apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../docker-compose.generated.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bitcoind
  name: bitcoind
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bitcoind
    spec:
      containers:
      - env:
        - name: BITCOIN_EXTRA_ARGS
          value: |
            deprecatedrpc=signrawtransaction
            rpcport=43782
            port=39388
            whitelist=0.0.0.0/0
        - name: BITCOIN_NETWORK
          value: testnet
        image: nicolasdorier/docker-bitcoin:0.17.0
        name: btcpayserver-bitcoind
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: bitcoin-datadir
      restartPolicy: Always
      volumes:
      - name: bitcoin-datadir
        persistentVolumeClaim:
          claimName: bitcoin-datadir
status: {}
