apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../docker-compose.generated.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: btcpayserver
  name: btcpayserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: btcpayserver
    spec:
      containers:
      - env:
        - name: BTCPAY_BIND
          value: 0.0.0.0:49392
        - name: BTCPAY_BTCEXPLORERURL
          value: http://nbxplorer:32838/
        - name: BTCPAY_BTCLIGHTNING
          value: type=clightning;server=unix://etc/clightning-bitcoin/lightning-rpc
        - name: BTCPAY_CHAINS
          value: ltc,btc
        - name: BTCPAY_EXTERNALURL
          value: https:///
        - name: BTCPAY_LTCEXPLORERURL
          value: http://nbxplorer:32838/
        - name: BTCPAY_LTCLIGHTNING
          value: type=clightning;server=unix://etc/clightning-litecoin/lightning-rpc
        - name: BTCPAY_NETWORK
          value: testnet
        - name: BTCPAY_POSTGRES
          value: User ID=postgres;Host=postgres;Port=5432;Database=btcpayservertestnet
        - name: BTCPAY_ROOTPATH
          value: /
        - name: BTCPAY_SSHKEYFILE
        - name: BTCPAY_SSHTRUSTEDFINGERPRINTS
        image: nicolasdorier/btcpayserver:1.0.3.4
        name: btcpayserver
        resources: {}
        volumeMounts:
        - mountPath: /datadir
          name: btcpay-datadir
        - mountPath: /root/.nbxplorer
          name: nbxplorer-datadir
        - mountPath: /etc/clightning-litecoin
          name: clightning-litecoin-datadir
        - mountPath: /etc/clightning-bitcoin
          name: clightning-bitcoin-datadir
      restartPolicy: Always
      volumes:
      - name: btcpay-datadir
        persistentVolumeClaim:
          claimName: btcpay-datadir
      - name: nbxplorer-datadir
        persistentVolumeClaim:
          claimName: nbxplorer-datadir
      - name: clightning-litecoin-datadir
        persistentVolumeClaim:
          claimName: clightning-litecoin-datadir
      - name: clightning-bitcoin-datadir
        persistentVolumeClaim:
          claimName: clightning-bitcoin-datadir
status: {}
