apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../docker-compose.generated.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: clightning-bitcoin
  name: clightning-bitcoin
spec:
  ports:
  - name: "9735"
    port: 9735
    targetPort: 9735
  selector:
    io.kompose.service: clightning-bitcoin
status:
  loadBalancer: {}
