  ##
  fullnameOverride: bitcoind
  #
  service: 
    rpcPort: 8332
    testnetPort: 18332
  persistence:
    enabled: true
    size: 30Gi
  configurationFile:
    bitcoin.conf: |-
      testnet=1
      whitelist=0.0.0.0/0
      server=1
      printtoconsole=1
      rpcuser=rpcuser
      rpcpassword=rpcpassword
