apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nifi-registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nifi-registry.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nifi-registry.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NIFI_REGISTRY_WEB_HTTP_HOST
              value: "0.0.0.0"
            - name: NIFI_REGISTRY_WEB_HTTP_PORT
              value: "18080"
          ports:
            - name: http
              containerPort: 18080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /nifi-registry
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /nifi-registry
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
          volumeMounts:
              - mountPath: /opt/registry.nifi
                name: registry-nifi-data
      # hostname: registry.nifi
      restartPolicy: Always
      volumes:
        - name: registry-nifi-data
          # persistentVolumeClaim:
          #   claimName: registry-nifi-data
          #kubectl create secret generic aksshare-secret --from-literal=azurestorageaccountname=STORAGE_ACCOUNT_NAME --from-literal=azurestorageaccountkey=STORAGE_ACCOUNT_KEY
          azureFile:
            secretName: aksshare-secret
            shareName: aksshare
            readOnly: false
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
