# Default values for matrix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##
synapse:
  hostname: "matrix"
  subdomain: "home"
  turn:
    uris: ""
    secret: ""

##
postgresql:
  enabled: true
  #
  nameOverride: postgres
  postgresqlUsername: matrix
  postgresqlPassword: changeme
  postgresqlDatabase: synapse
#