# Default values for matrix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##
synapse:
  hostname: "matrix"
  subdomain: "home"
  turn:
    uris: ""
    secret: ""
  #proxy
  httpProxy: "http://host.docker.internal:18080/"
  httpsProxy: "http://host.docker.internal:18080/"
  noProxy: "localhost,127.0.0.1,.local"

##
postgresql:
  enabled: true
  #
  nameOverride: postgres
  postgresqlUsername: matrix
  postgresqlPassword: changeme
  postgresqlDatabase: synapse
#