apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightningd.fullname" . }}
  labels:
    app: {{ include "lightningd.name" . }}
    chart: {{ include "lightningd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.chargePort }}
      targetPort: charge
      protocol: TCP
      name: charge
  selector:
    app: {{ include "lightningd.name" . }}
    release: {{ .Release.Name }}
