apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out synapse-riot
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: coturn
    spec:
      containers:
      - image: instrumentisto/coturn
        name: coturn
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 3478
        - containerPort: 3479
          protocol: UDP
        - containerPort: 3479
        - containerPort: 5349
          protocol: UDP
        - containerPort: 5349
        - containerPort: 5350
          protocol: UDP
        - containerPort: 5350
        - containerPort: 65535
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/coturn
          name: coturn-data
      hostname: coturn
      restartPolicy: Always
      volumes:
      - name: coturn-data
        persistentVolumeClaim:
          claimName: coturn-data
status: {}
