apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out synapse-riot
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  ports:
  - name: "3478"
    port: 3478
    protocol: UDP
    targetPort: 3478
  - name: 3478-tcp
    port: 3478
    targetPort: 3478
  - name: "3479"
    port: 3479
    protocol: UDP
    targetPort: 3479
  - name: 3479-tcp
    port: 3479
    targetPort: 3479
  - name: "5349"
    port: 5349
    protocol: UDP
    targetPort: 5349
  - name: 5349-tcp
    port: 5349
    targetPort: 5349
  - name: "5350"
    port: 5350
    protocol: UDP
    targetPort: 5350
  - name: 5350-tcp
    port: 5350
    targetPort: 5350
  - name: "49152"
    port: 49152
    protocol: UDP
    targetPort: 65535
  selector:
    io.kompose.service: coturn
status:
  loadBalancer: {}
