apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --out synapse-riot
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: riot
  name: riot
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8765
  selector:
    io.kompose.service: riot
status:
  loadBalancer: {}
