dependencies:
- name: postgresql
  version: 2.3.4
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: postgresql.enabled
- name: mariadb
  version: 5.2.3
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: mariadb.enabled
- name: bitcoind
  version: 0.1.3
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: bitcoind.enabled
- name: lightningd
  version: 0.1.0
  repository: https://asperitus.github.io/helm
  condition: lightningd.enabled
- name: btcpayd
  version: 0.1.0
  repository: https://asperitus.github.io/helm
  condition: btcpayd.enabled
- name: wordpress
  version: 3.3.0
  repository: https://asperitus.github.io/helm
  condition: wordpress.enabled