# Default values for btcstore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##
postgresql:
  enabled: true
  #
  nameOverride: db
    postgresqlUsername: postgres
    postgresqlPassword: secretPassword
    postgresqlDatabase: btcpayserver

##
mariadb:
  enabled: true
  #
  nameOverride: db
  service.port: 3306
  rootUser:
    password: secretPassword
  db:
    user: mysql
    password: secretPassword

##
bitcoind:
  enabled: true
  #
  fullnameOverride: bitcoind
  service: 
    rpcPort: 8332
    testnetPort: 18332
  persistence:
    enabled: true
    size: 30Gi
  configurationFile:
    bitcoin.conf: |-
      testnet=1
      whitelist=0.0.0.0/0
      server=1
      printtoconsole=1
      rpcuser=rpcuser
      rpcpassword=rpcpassword

##
lightningd:
  enabled: true
  #
  persistence:
    size: 10Gi

##
btcpayd:
  enabled: true
  #
  persistence:
    size: 2Gi
  args:
    network: testnet
    externalUrl: $URL
  #
  foregate:
    enabled: true
    port: 5080
    url: $URL
    proxy: $http_proxy

##
wordpress:
  enabled: true
  #
  nameOverride: store
  serviceType: ClusterIP
  wordpressUsername: admin
  wordpressPassword: password
  mariadb.enabled: false
  externalDatabase:
    host: mysql-db.db
    port: 3306
    user: mysql
    password: secretPassword
    database: my_database
  foregate:
    enabled: true
    port: 5080
    url: $URL
    proxy: $http_proxy

####
