apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bitcoind
  name: bitcoind
spec:
  ports:
  - name: "18333"
    port: 18333
    targetPort: 18333
  selector:
    io.kompose.service: bitcoind
status:
  loadBalancer: {}
