apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: clightning-bitcoin
  name: clightning-bitcoin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: clightning-bitcoin
    spec:
      containers:
      - args:
        - --bitcoin-rpcconnect=bitcoind
        - --bitcoin-rpcuser=rpcuser
        - --bitcoin-rpcpassword=rpcpass
        - --network=testnet
        - --alias=myawesomenode
        - --log-level=debug
        env:
        - name: EXPOSE_TCP
          value: "true"
        image: elementsproject/lightningd
        name: lightningd
        ports:
        - containerPort: 9735
        resources: {}
        volumeMounts:
        - mountPath: /root/.lightning
          name: clightning-bitcoin-datadir
        - mountPath: /etc/bitcoin
          name: bitcoin-datadir
      restartPolicy: Always
      volumes:
      - name: clightning-bitcoin-datadir
        persistentVolumeClaim:
          claimName: clightning-bitcoin-datadir
      - name: bitcoin-datadir
        persistentVolumeClaim:
          claimName: bitcoin-datadir
status: {}
